USE [JamifyDB]
GO

/****** Object:  Table [dbo].[MediaData]    Script Date: 05.03.2023 20:09:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MediaData](
	[Id] [uniqueidentifier] NOT NULL,
	[MediaBytes] [varbinary](max) NOT NULL,
	[MediaType] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_MediaData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MediaData] ADD  CONSTRAINT [DF_MediaData_Id]  DEFAULT (newid()) FOR [Id]
GO

